export const skillsArray = [
  // {
  //   title: "JavaScript",
  //   text: "I master JavaScript vanilla at a fairly high level and can use my analytic skills to create well-functioning solutions for an interactive website. Whenever it's convenient I use HTML DOM to make the HTML doc as neat as possible. I have some experience to React, and will focus on strenghten these skills in the upcoming months.",
  //   keyword: ["React", "HTML DOM"],
  // },
  // {
  //   title: "HTML",
  //   text: "Since I was a child, when I build my Lego worlds, I have always liked the idea of building stuff. With HTML I have the opportunity to create cool semantic constructions with nice use of BEM-classes.",
  //   keyword: ["Semantic", "BEM-classes"],
  // },
  // {
  //   title: "CSS",
  //   text: "Lately I have gained good experience using sass in my projects. This simplifies the work in css, and makes the scripts more neat. In smaller projects I have gained some experience using the frameworks Bootstrap and Tailwind. I will focus to gain more experience on these frameworks in further projects.",
  //   keyword: ["SCSS", "Bootstrap", "Tailwind"],
  // },
  // {
  //   title: "Design",
  //   text: "At present time I've designed all my projects. With tools as Adobe XD, and following design principles I manage to create websites that looks nice with a good usability, where both UX and UI is in focus.",
  //   keyword: ["Usability", "UX", "UI"],
  // },

  {
    title: "JavaScript",
    text: "I master JS vanilla on a solid level where I can use my commitment to create well-functioning solutions. I've gradually gained experience with React. I enjoy working with it, and plan to use it in the upcoming projects, Disc Golf Tour and Hangman World. From the studies I also gained some experience with NextJS and TypeScript, and further down the road I want to build some projects with them.",
    keyword: ["React,", "TypeScript,", "NextJS"],
  },
  {
    title: "CSS",
    text: "The newer projects are styled with Sass. I enjoy the opportunity it gives, and by using BEM class it let me build neat and concise styling scripts. Have built some projects with Bootstrap, such as the project “Weatherish”. Some experience with Tailwind, but not in any bigger project yet.",
    keyword: ["Sass,", "Bootstrap,", "Tailwind"],
  },
  {
    title: "Design",
    text: "At present time I've designed all my projects. With tools as Adobe XD, and following design principles I manage to create websites that looks nice with a good usability, where both UX and UI is in focus.",
    keyword: ["Adobe XD,", "UX,", "UI"],
  },
  {
    title: "Backend",
    text: " I've built several Rest API's through services such as Strapi and WordPress. Also have some experience with SQL from when I studied at Molde University College. However, it's been a while and I would need to strengthen this knowledge before I can start to implement it to my projects. The goal is to become a full stack dev in the future.",
    keyword: ["Rest API,", "SQL"],
  },
];

export const featuredArray = [
  // {
  //   id: "0",
  //   title: "Running Shoes",
  //   text: "E-commerce website. Well functioned shopping cart. Where I've used a combo of local storage and Strapi API to make the website run well. Also created an admin login so that products can be added or edited in the website.",
  //   image: "../../images/runningshoes.jpg",
  //   url: "https://running-shoes.netlify.app",
  // },
  {
    id: "0",
    title: "Holidaze",
    text: "Final exam in my studies. Built a booking website for the Bergen area. Strapi and heroku as back-end. The website consists of both visitor- and admin-facing pages. It let visitors send enquiries to accommodation owners, post/read reviews of accommodation.",
    image: "../../images/holidaze.jpg",
    url: "https://holidays.netlify.app",
    github: "https://github.com/lassopicasso/exam-2.git",
    javascript: "React",
    css: "Scss",
  },
  {
    id: "1",
    title: "Blogland",
    text: "A design that covers nicely the theme of this website. Easy to navigate with sort functions that gives a good usability when searching for content. The website use headless CMS from WordPress.",
    image: "../../images/blog.jpg",
    url: "https://bloglaand.netlify.app",
    github: "https://github.com/lassopicasso/Project-Exam---updated.git",
    javascript: "JS Vanilla",
    css: "CSS",
  },
  // {
  //   id: "1",
  //   title: "Weatherish",
  //   text: "React Project. Weather forecast which includes current weather info, 24 hours chart, 8 days interactive forecast and a favorite page with your chosen places. Much work laid down on handle the data from API by using React.",
  //   image: "../../images/weatherforecast.jpg",
  //   url: "https://forecastsweather.netlify.app/",
  // },
];

export const projectsArray = [
  {
    title: "Holidaze",
    theme: "Booking service",
    date: "2022, 10, 03",
    image: "../../images/holidaze.jpg",
    url: "https://holidays.netlify.app",
    github: "https://github.com/lassopicasso/exam-2.git",
    javascript: "React",
    css: "Scss",
  },
  {
    title: "Weatherish",
    theme: "Weather service",
    date: "2022, 07, 30",
    image: "../../images/weatherforecast.jpg",
    url: "https://forecastsweather.netlify.app",
    github: "https://github.com/lassopicasso/WeatherForecast---React-Project.git",
    javascript: "React",
    css: "Bootstrap",
  },
  {
    title: "Running Shoes",
    theme: "E-commerce",
    date: "2022, 03, 06",
    image: "../../images/runningshoes.jpg",
    url: "https://running-shoes.netlify.app",
    github: "https://github.com/lassopicasso/running-shoes.git",
    javascript: "Vanilla",
    css: "Scss",
  },
  {
    title: "Community Museum",
    theme: "Museum",
    date: "2021, 02, 28",
    image: "../../images/museum.jpg",
    url: "https://communitymuseumm.netlify.app",
    github: "https://github.com/lassopicasso/semester-project-1-updated.git",
    javascript: "Vanilla",
    css: "Vanilla",
  },
  {
    title: "Blogland",
    theme: "Blog",
    date: "2021, 10, 09",
    image: "../../images/blog.jpg",
    url: "https://bloglaand.netlify.app",
    github: "https://github.com/lassopicasso/Project-Exam---updated.git",
    javascript: "Vanilla",
    css: "Vanilla",
  },
  {
    title: "RainyDays",
    theme: "E-commerce",
    date: "2021, 02, 06",
    image: "../../images/rainydays.jpg",
    url: "https://rainydayss.netlify.app",
    github: "https://github.com/lassopicasso/cross-course-project-update.git",
    javascript: "Vanilla",
    css: "Vanilla",
  },
];
