export const skillsArray = [
  {
    title: "JavaScript",
    text: "I master JS vanilla on a solid level where I can use my commitment to create well-functioning solutions. I've gradually gained experience with React. I enjoy working with it, and plan to use it in the upcoming projects; Disc Golf Tour and Hangman World. <span class='text--block'>From the studies I also gained some experience with NextJS and TypeScript, and further down the road I would like to build some projects using them.</span>",
    keyword: ["React,", "TypeScript,", "NextJS"],
  },
  {
    title: "CSS",
    text: "The newer projects are styled with Sass. It has some nice features and by using BEM class it let me build neat and concise styling scripts. <span class='text--block'> I have built some projects with Bootstrap, e.g. “Weatherish”.</span> And have some experience with Tailwind, but not yet in any larger project.",
    keyword: ["Sass,", "Bootstrap,", "Tailwind"],
  },
  {
    title: "Design",
    text: "At present time I've designed all my projects. With tools like Adobe XD, and following design principles, I manage to create websites that looks nice with a good usability, where both UX and UI is in focus.",
    keyword: ["Adobe XD,", "UX,", "UI"],
  },
  {
    title: "Backend",
    text: " I've built several Rest API's through services such as Strapi and WordPress. Also have some experience with database design and SQL from when I studied at Molde University College. Unfortunately, it's been a while. Need to strengten this knowledge before I can start implement it to larger projects. That is my goal.",
    keyword: ["Rest API,", "SQL"],
  },
];

export const featuredArray = [
  {
    id: "0",
    title: "Christmas Games",
    text: "A collection of Christmas games. It's built with React and styled with CSS modules. It's a fun project that I built for the Christmas season for my nephews and aiming for a full release christmas 2024.",
    image: "../../images/christmasgames.jpg",
    url: "https://christmasGames.netlify.app/",
    github: "/",
    githubName: "",
    javascript: "React",
    css: "CSS modules",
  },
  {
    id: "1",
    title: "Hangman World",
    text: "Hangman game that makes geography fun. Choose a continent or the world. It use an API with capitals around the world. If the player gets a top 10 score, it will be saved in a REST API that is built in strapi and displayed on the top 10-page",
    image: "../../images/hangman-world.jpg",
    url: "https://hangman-world.netlify.app/",
    github: "https://github.com/lassopicasso/hangman-world.git",
    githubName: "HangMan",
    javascript: "React",
    css: "Scss",
  },
  // {
  //   id: "2",
  //   title: "Holidaze",
  //   text: "Final exam in my studies. Built a booking website for the Bergen area. Strapi and heroku as back-end. The website consists of both visitor- and admin-facing pages. It let visitors send enquiries to accommodation owners, post/read reviews of accommodation.",
  //   image: "../../images/holidaze.jpg",
  //   url: "https://holidays.netlify.app",
  //   github: "https://github.com/lassopicasso/exam-2.git",
  //   javascript: "React",
  //   css: "Scss",
  // },
  // {
  //   id: "1",
  //   title: "Blogland",
  //   text: "A design that covers nicely the theme of this website. Easy to navigate with sort functions that gives a good usability when searching for content. The website use headless CMS from WordPress.",
  //   image: "../../images/blog.jpg",
  //   url: "https://bloglaand.netlify.app",
  //   github: "https://github.com/lassopicasso/Project-Exam---updated.git",
  //   javascript: "JS Vanilla",
  //   css: "CSS",
  // },
  // {
  //   id: "1",
  //   title: "Weatherish",
  //   text: "React Project. Weather forecast which includes current weather info, 24 hours chart, 8 days interactive forecast and a favorite page with your chosen places. Much work laid down on handle the data from API by using React.",
  //   image: "../../images/weatherforecast.jpg",
  //   url: "https://forecastsweather.netlify.app/",
  // },
];

export const projectsArray = [
  {
    title: "Christmas Games",
    theme: "Memory game",
    date: "2023, 12, 23",
    image: "../../images/christmasgames.jpg",
    url: "https://christmasGames.netlify.app/",
    github: "/",
    githubName: "",
    javascript: "React TypeScript",
    css: "CSS modules",
  },
  {
    title: "Hangman World",
    theme: "Quiz game",
    date: "2022, 11, 05",
    image: "../../images/hangman-world.jpg",
    url: "https://hangman-world.netlify.app/",
    github: "https://github.com/lassopicasso/hangman-world.git",
    githubName: "Repo: Hangman World",
    javascript: "React",
    css: "Scss",
  },
  {
    title: "Holidaze",
    theme: "Booking service",
    date: "2022, 10, 03",
    image: "../../images/holidaze.jpg",
    url: "https://holidays.netlify.app",
    github: "https://github.com/lassopicasso/exam-2.git",
    githubName: "Repo: Holidaze",
    javascript: "React",
    css: "Scss",
  },
  {
    title: "Weatherish",
    theme: "Weather service",
    date: "2022, 07, 30",
    image: "../../images/weatherforecast.jpg",
    url: "https://forecastsweather.netlify.app",
    github:
      "https://github.com/lassopicasso/WeatherForecast---React-Project.git",
    githubName: "Whatever Weather",
    javascript: "React",
    css: "Bootstrap",
  },
  {
    title: "Running Shoes",
    theme: "E-commerce",
    date: "2022, 03, 06",
    image: "../../images/runningshoes.jpg",
    url: "https://running-shoes.netlify.app",
    github: "https://github.com/lassopicasso/running-shoes.git",
    githubName: "Flying Shoes",
    javascript: "Vanilla",
    css: "Scss",
  },
  {
    title: "Community Museum",
    theme: "Museum",
    date: "2021, 02, 28",
    image: "../../images/museum.jpg",
    url: "https://communitymuseumm.netlify.app",
    github: "https://github.com/lassopicasso/semester-project-1-updated.git",
    githubName: "Museum of Exploring",
    javascript: "Vanilla",
    css: "Vanilla",
  },
  {
    title: "Blogland",
    theme: "Blog",
    date: "2021, 10, 09",
    image: "../../images/blog.jpg",
    url: "https://bloglaand.netlify.app",
    github: "https://github.com/lassopicasso/Project-Exam---updated.git",
    githubName: "Landblog",
    javascript: "Vanilla",
    css: "Vanilla",
  },
  {
    title: "RainyDays",
    theme: "E-commerce",
    date: "2021, 02, 06",
    image: "../../images/rainydays.jpg",
    url: "https://rainydayss.netlify.app",
    github: "https://github.com/lassopicasso/cross-course-project-update.git",
    githubName: "Bergen",
    javascript: "Vanilla",
    css: "Vanilla",
  },
];
